name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy files
        run: |
          python -m pip install --upgrade pip
          pip install flask
          chmod +rwx main.py
          python3 main.py
