name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 3.71.101.165
        username: ec2-user
        key: ${{ secrets.KEY }}
        script: whoami
