name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key
          chmod 600 key

      - name: Copy files via ssh
        run: |
          scp -i key $GITHUB_WORKSPACE/main.py loco2@192.168.81.130:/home/loco2
