name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Copy files via ssh
      run: |
       ls -l $GITHUB_WORKSPACE
       python3 main.py
   
