name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy files
        run: sshpass -p ${{ secrets.PASSWORD }} scp $GITHUB_WORKSPACE/main.py loco2@192.168.81.130:/home/loco2
