name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy files via ssh
        run: |
          chmod 600 key
          scp -i key main.py loco2@192.168.81.130:/home/loco2
