name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: List files in repository
      run: ls -R $GITHUB_WORKSPACE

    - name: Copy files via ssh
      run: |
        ls
