name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Add other necessary build steps here

      - name: Setup SSH key
        run: |
          echo "${{ secrets.KEY }}" > key
          chmod 600 key

      - name: Copy files via ssh
        run: |
          cat key
          cat main.py
