name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: copy file via ssh password
       uses: appleboy/scp-action@v0.1.4
        with:
           host: example.com
           username: foo
           password: bar
           port: 22
           source: "main.py"
           target: your_server_target_folder_path
