name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: List files in repository
      run: ls -la
     
    - name: files in repository
      run: chmod 400 key 

    - name: Copy files via ssh
      run: scp -i key main.py loco2@192.168.81.130:/home/loco2
