name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Zip the scripts
      run: |
        zip -r scripts.zip . -i main.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: scripts
        path: scripts.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: scripts
        path: ./artifacts
        
    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: 192.168.81.130
        username: loco2
        password: loco12
        source: "./artifacts/scripts.zip"
        target: "/path/to/deploy"

    - name: Execute script on the VM
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.81.130
        username: loco2
        password: loco12
        script: |
          cd /path/to/deploy
          unzip scripts.zip
          python main.py   
   
