name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v.0.1.3
      with:
        host: 192.168.81.131
        username: loco3
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
